# Generated by Django 4.1.6 on 2023-02-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="highlighted",
        ),
    ]
