# Generated by Django 4.1.6 on 2023-02-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "post_category",
                    models.CharField(
                        choices=[("BTC", "Bitcoin"), ("BLOCK", "BlockChain News")],
                        default="BLOCK",
                        max_length=5,
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
