# Generated by Django 4.1.6 on 2023-02-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guide",
            options={"ordering": ["-id"]},
        ),
    ]
